# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evb1000viewer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EVB1000ViewerMainWindow(object):
    def setupUi(self, EVB1000ViewerMainWindow):
        EVB1000ViewerMainWindow.setObjectName("EVB1000ViewerMainWindow")
        EVB1000ViewerMainWindow.resize(648, 432)
        self.centralwidget = QtWidgets.QWidget(EVB1000ViewerMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.connectedTagsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.connectedTagsGroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.connectedTagsGroupBox.setObjectName("connectedTagsGroupBox")
        self.connectedTagsGroupBoxLayout = QtWidgets.QVBoxLayout(self.connectedTagsGroupBox)
        self.connectedTagsGroupBoxLayout.setObjectName("connectedTagsGroupBoxLayout")
        self.connectedTagsScrollArea = QtWidgets.QScrollArea(self.connectedTagsGroupBox)
        self.connectedTagsScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.connectedTagsScrollArea.setWidgetResizable(True)
        self.connectedTagsScrollArea.setObjectName("connectedTagsScrollArea")
        self.connectedTagsScrollAreaWidget = QtWidgets.QWidget()
        self.connectedTagsScrollAreaWidget.setEnabled(True)
        self.connectedTagsScrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 276, 125))
        self.connectedTagsScrollAreaWidget.setObjectName("connectedTagsScrollAreaWidget")
        self.connectedTagsScrollAreaWidgetLayout = QtWidgets.QVBoxLayout(self.connectedTagsScrollAreaWidget)
        self.connectedTagsScrollAreaWidgetLayout.setContentsMargins(0, 0, 15, 0)
        self.connectedTagsScrollAreaWidgetLayout.setObjectName("connectedTagsScrollAreaWidgetLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.connectedTagsScrollAreaWidgetLayout.addItem(spacerItem)
        self.connectedTagsScrollArea.setWidget(self.connectedTagsScrollAreaWidget)
        self.connectedTagsGroupBoxLayout.addWidget(self.connectedTagsScrollArea)
        self.connectedTagsRecordButtonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.connectedTagsRecordButtonsHorizontalLayout.setObjectName("connectedTagsRecordButtonsHorizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connectedTagsRecordButtonsHorizontalLayout.addItem(spacerItem1)
        self.connectedTagsRecordButton = QtWidgets.QPushButton(self.connectedTagsGroupBox)
        self.connectedTagsRecordButton.setObjectName("connectedTagsRecordButton")
        self.connectedTagsRecordButtonsHorizontalLayout.addWidget(self.connectedTagsRecordButton)
        self.connectedTagsStopButton = QtWidgets.QPushButton(self.connectedTagsGroupBox)
        self.connectedTagsStopButton.setObjectName("connectedTagsStopButton")
        self.connectedTagsRecordButtonsHorizontalLayout.addWidget(self.connectedTagsStopButton)
        self.connectedTagsGroupBoxLayout.addLayout(self.connectedTagsRecordButtonsHorizontalLayout)
        self.gridLayout.addWidget(self.connectedTagsGroupBox, 1, 1, 1, 1)
        self.matPlotGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.matPlotGroupBox.setObjectName("matPlotGroupBox")
        self.matPlotGroupBoxLayout = QtWidgets.QVBoxLayout(self.matPlotGroupBox)
        self.matPlotGroupBoxLayout.setObjectName("matPlotGroupBoxLayout")
        self.gridLayout.addWidget(self.matPlotGroupBox, 1, 0, 1, 1)
        self.logGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.logGroupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.logGroupBox.setObjectName("logGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.logGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logScrollArea = QtWidgets.QScrollArea(self.logGroupBox)
        self.logScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.logScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.logScrollArea.setWidgetResizable(True)
        self.logScrollArea.setObjectName("logScrollArea")
        self.logScrollAreaWidgetContents = QtWidgets.QWidget()
        self.logScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 600, 108))
        self.logScrollAreaWidgetContents.setObjectName("logScrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.logScrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logLabel = QtWidgets.QLabel(self.logScrollAreaWidgetContents)
        self.logLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.logLabel.setText("")
        self.logLabel.setObjectName("logLabel")
        self.verticalLayout_2.addWidget(self.logLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.logScrollArea.setWidget(self.logScrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.logScrollArea)
        self.gridLayout.addWidget(self.logGroupBox, 2, 0, 1, 2)
        EVB1000ViewerMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EVB1000ViewerMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        EVB1000ViewerMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EVB1000ViewerMainWindow)
        self.statusbar.setObjectName("statusbar")
        EVB1000ViewerMainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(EVB1000ViewerMainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(EVB1000ViewerMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(EVB1000ViewerMainWindow)
        QtCore.QMetaObject.connectSlotsByName(EVB1000ViewerMainWindow)

    def retranslateUi(self, EVB1000ViewerMainWindow):
        _translate = QtCore.QCoreApplication.translate
        EVB1000ViewerMainWindow.setWindowTitle(_translate("EVB1000ViewerMainWindow", "EVB1000 Tag Viewer"))
        self.connectedTagsGroupBox.setTitle(_translate("EVB1000ViewerMainWindow", "Connected Tags"))
        self.connectedTagsRecordButton.setText(_translate("EVB1000ViewerMainWindow", "Record"))
        self.connectedTagsStopButton.setText(_translate("EVB1000ViewerMainWindow", "Stop"))
        self.matPlotGroupBox.setTitle(_translate("EVB1000ViewerMainWindow", "Plot"))
        self.logGroupBox.setTitle(_translate("EVB1000ViewerMainWindow", "Log"))
        self.menuFile.setTitle(_translate("EVB1000ViewerMainWindow", "&File"))
        self.menuHelp.setTitle(_translate("EVB1000ViewerMainWindow", "&Help"))
        self.actionQuit.setText(_translate("EVB1000ViewerMainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("EVB1000ViewerMainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("EVB1000ViewerMainWindow", "&About"))

