# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tag_item_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tagItem(object):
    def setupUi(self, tagItem):
        tagItem.setObjectName("tagItem")
        tagItem.resize(212, 283)
        tagItem.setMaximumSize(QtCore.QSize(16777215, 283))
        tagItem.setFrameShape(QtWidgets.QFrame.Box)
        tagItem.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(tagItem)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deviceGroupBox = QtWidgets.QGroupBox(tagItem)
        self.deviceGroupBox.setObjectName("deviceGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.deviceGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tagIdLabel = QtWidgets.QLabel(self.deviceGroupBox)
        self.tagIdLabel.setObjectName("tagIdLabel")
        self.gridLayout.addWidget(self.tagIdLabel, 0, 0, 1, 1)
        self.tagIdLabelValue = QtWidgets.QLabel(self.deviceGroupBox)
        self.tagIdLabelValue.setObjectName("tagIdLabelValue")
        self.gridLayout.addWidget(self.tagIdLabelValue, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.portLabelValue = QtWidgets.QLabel(self.deviceGroupBox)
        self.portLabelValue.setObjectName("portLabelValue")
        self.gridLayout.addWidget(self.portLabelValue, 1, 3, 1, 1)
        self.portLabel = QtWidgets.QLabel(self.deviceGroupBox)
        self.portLabel.setObjectName("portLabel")
        self.gridLayout.addWidget(self.portLabel, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.deviceGroupBox)
        self.positionGroupBox = QtWidgets.QGroupBox(tagItem)
        self.positionGroupBox.setObjectName("positionGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.positionGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.yLabelValue = QtWidgets.QLabel(self.positionGroupBox)
        self.yLabelValue.setObjectName("yLabelValue")
        self.gridLayout_2.addWidget(self.yLabelValue, 1, 2, 1, 1)
        self.yLabel = QtWidgets.QLabel(self.positionGroupBox)
        self.yLabel.setObjectName("yLabel")
        self.gridLayout_2.addWidget(self.yLabel, 1, 0, 1, 1)
        self.xLabelValue = QtWidgets.QLabel(self.positionGroupBox)
        self.xLabelValue.setObjectName("xLabelValue")
        self.gridLayout_2.addWidget(self.xLabelValue, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        self.xLabel = QtWidgets.QLabel(self.positionGroupBox)
        self.xLabel.setObjectName("xLabel")
        self.gridLayout_2.addWidget(self.xLabel, 0, 0, 1, 1)
        self.zLabel = QtWidgets.QLabel(self.positionGroupBox)
        self.zLabel.setObjectName("zLabel")
        self.gridLayout_2.addWidget(self.zLabel, 2, 0, 1, 1)
        self.zLabelValue = QtWidgets.QLabel(self.positionGroupBox)
        self.zLabelValue.setObjectName("zLabelValue")
        self.gridLayout_2.addWidget(self.zLabelValue, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.positionGroupBox)
        self.recordLayout = QtWidgets.QHBoxLayout()
        self.recordLayout.setObjectName("recordLayout")
        self.recordingLabel = QtWidgets.QLabel(tagItem)
        self.recordingLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.recordingLabel.setFont(font)
        self.recordingLabel.setStyleSheet("color : rgb(255, 0, 0);")
        self.recordingLabel.setObjectName("recordingLabel")
        self.recordLayout.addWidget(self.recordingLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.recordLayout.addItem(spacerItem5)
        self.recordCheckbox = QtWidgets.QCheckBox(tagItem)
        self.recordCheckbox.setToolTip("")
        self.recordCheckbox.setTristate(False)
        self.recordCheckbox.setObjectName("recordCheckbox")
        self.recordLayout.addWidget(self.recordCheckbox, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.recordLayout)

        self.retranslateUi(tagItem)
        QtCore.QMetaObject.connectSlotsByName(tagItem)

    def retranslateUi(self, tagItem):
        _translate = QtCore.QCoreApplication.translate
        tagItem.setWindowTitle(_translate("tagItem", "Frame"))
        self.deviceGroupBox.setTitle(_translate("tagItem", "Device"))
        self.tagIdLabel.setText(_translate("tagItem", "Tag ID:"))
        self.tagIdLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.portLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.portLabel.setText(_translate("tagItem", "Port:"))
        self.positionGroupBox.setTitle(_translate("tagItem", "Position"))
        self.yLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.yLabel.setText(_translate("tagItem", "y (m):"))
        self.xLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.xLabel.setText(_translate("tagItem", "x (m):"))
        self.zLabel.setText(_translate("tagItem", "z (m):"))
        self.zLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.recordingLabel.setText(_translate("tagItem", "Recording..."))
        self.recordCheckbox.setText(_translate("tagItem", "Record"))

