# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tag_item_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_tagItem(object):
    def setupUi(self, tagItem):
        tagItem.setObjectName("tagItem")
        tagItem.resize(398, 247)
        tagItem.setMaximumSize(QtCore.QSize(16777215, 247))
        tagItem.setFrameShape(QtWidgets.QFrame.Box)
        tagItem.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(tagItem)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deviceGroupBox = QtWidgets.QGroupBox(tagItem)
        self.deviceGroupBox.setObjectName("deviceGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.deviceGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tagIdLabelValue = QtWidgets.QLabel(self.deviceGroupBox)
        self.tagIdLabelValue.setMinimumSize(QtCore.QSize(50, 0))
        self.tagIdLabelValue.setObjectName("tagIdLabelValue")
        self.gridLayout.addWidget(self.tagIdLabelValue, 0, 2, 1, 1)
        self.tagIdLabel = QtWidgets.QLabel(self.deviceGroupBox)
        self.tagIdLabel.setObjectName("tagIdLabel")
        self.gridLayout.addWidget(self.tagIdLabel, 0, 0, 1, 1)
        self.portLabelValue = QtWidgets.QLabel(self.deviceGroupBox)
        self.portLabelValue.setMinimumSize(QtCore.QSize(50, 0))
        self.portLabelValue.setObjectName("portLabelValue")
        self.gridLayout.addWidget(self.portLabelValue, 0, 5, 1, 1)
        self.portLabel = QtWidgets.QLabel(self.deviceGroupBox)
        self.portLabel.setObjectName("portLabel")
        self.gridLayout.addWidget(self.portLabel, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.deviceGroupBox)
        self.positionGroupBox = QtWidgets.QGroupBox(tagItem)
        self.positionGroupBox.setObjectName("positionGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.positionGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.yLabelValue = QtWidgets.QLabel(self.positionGroupBox)
        self.yLabelValue.setMinimumSize(QtCore.QSize(50, 0))
        self.yLabelValue.setObjectName("yLabelValue")
        self.gridLayout_2.addWidget(self.yLabelValue, 0, 5, 1, 1)
        self.xLabelValue = QtWidgets.QLabel(self.positionGroupBox)
        self.xLabelValue.setMinimumSize(QtCore.QSize(50, 0))
        self.xLabelValue.setObjectName("xLabelValue")
        self.gridLayout_2.addWidget(self.xLabelValue, 0, 1, 1, 1)
        self.zLabel = QtWidgets.QLabel(self.positionGroupBox)
        self.zLabel.setObjectName("zLabel")
        self.gridLayout_2.addWidget(self.zLabel, 0, 7, 1, 1)
        self.yLabel = QtWidgets.QLabel(self.positionGroupBox)
        self.yLabel.setObjectName("yLabel")
        self.gridLayout_2.addWidget(self.yLabel, 0, 4, 1, 1)
        self.zLabelValue = QtWidgets.QLabel(self.positionGroupBox)
        self.zLabelValue.setMinimumSize(QtCore.QSize(50, 0))
        self.zLabelValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.zLabelValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.zLabelValue.setObjectName("zLabelValue")
        self.gridLayout_2.addWidget(self.zLabelValue, 0, 8, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.xLabel = QtWidgets.QLabel(self.positionGroupBox)
        self.xLabel.setObjectName("xLabel")
        self.gridLayout_2.addWidget(self.xLabel, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.positionGroupBox)
        self.estimateGroupBox = QtWidgets.QGroupBox(tagItem)
        self.estimateGroupBox.setObjectName("estimateGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.estimateGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.yEstLabel = QtWidgets.QLabel(self.estimateGroupBox)
        self.yEstLabel.setObjectName("yEstLabel")
        self.gridLayout_4.addWidget(self.yEstLabel, 0, 3, 1, 1)
        self.zEstLabelValue = QtWidgets.QLabel(self.estimateGroupBox)
        self.zEstLabelValue.setMinimumSize(QtCore.QSize(50, 0))
        self.zEstLabelValue.setObjectName("zEstLabelValue")
        self.gridLayout_4.addWidget(self.zEstLabelValue, 0, 7, 1, 1)
        self.xEstLabelValue = QtWidgets.QLabel(self.estimateGroupBox)
        self.xEstLabelValue.setMinimumSize(QtCore.QSize(50, 0))
        self.xEstLabelValue.setObjectName("xEstLabelValue")
        self.gridLayout_4.addWidget(self.xEstLabelValue, 0, 1, 1, 1)
        self.zEstLabel = QtWidgets.QLabel(self.estimateGroupBox)
        self.zEstLabel.setObjectName("zEstLabel")
        self.gridLayout_4.addWidget(self.zEstLabel, 0, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 2, 1, 1)
        self.xEstLabel = QtWidgets.QLabel(self.estimateGroupBox)
        self.xEstLabel.setObjectName("xEstLabel")
        self.gridLayout_4.addWidget(self.xEstLabel, 0, 0, 1, 1)
        self.yEstLabelValue = QtWidgets.QLabel(self.estimateGroupBox)
        self.yEstLabelValue.setMinimumSize(QtCore.QSize(50, 0))
        self.yEstLabelValue.setObjectName("yEstLabelValue")
        self.gridLayout_4.addWidget(self.yEstLabelValue, 0, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 5, 1, 1)
        self.rollEstLabel = QtWidgets.QLabel(self.estimateGroupBox)
        self.rollEstLabel.setObjectName("rollEstLabel")
        self.gridLayout_4.addWidget(self.rollEstLabel, 1, 0, 1, 1)
        self.rollEstLabelValue = QtWidgets.QLabel(self.estimateGroupBox)
        self.rollEstLabelValue.setMinimumSize(QtCore.QSize(50, 0))
        self.rollEstLabelValue.setObjectName("rollEstLabelValue")
        self.gridLayout_4.addWidget(self.rollEstLabelValue, 1, 1, 1, 1)
        self.pitchEstLabel = QtWidgets.QLabel(self.estimateGroupBox)
        self.pitchEstLabel.setObjectName("pitchEstLabel")
        self.gridLayout_4.addWidget(self.pitchEstLabel, 1, 3, 1, 1)
        self.pitchEstLabelValue = QtWidgets.QLabel(self.estimateGroupBox)
        self.pitchEstLabelValue.setMinimumSize(QtCore.QSize(50, 0))
        self.pitchEstLabelValue.setObjectName("pitchEstLabelValue")
        self.gridLayout_4.addWidget(self.pitchEstLabelValue, 1, 4, 1, 1)
        self.yawEstLabel = QtWidgets.QLabel(self.estimateGroupBox)
        self.yawEstLabel.setObjectName("yawEstLabel")
        self.gridLayout_4.addWidget(self.yawEstLabel, 1, 6, 1, 1)
        self.yawEstLabelValue = QtWidgets.QLabel(self.estimateGroupBox)
        self.yawEstLabelValue.setMinimumSize(QtCore.QSize(50, 0))
        self.yawEstLabelValue.setObjectName("yawEstLabelValue")
        self.gridLayout_4.addWidget(self.yawEstLabelValue, 1, 7, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 1, 5, 1, 1)
        self.verticalLayout.addWidget(self.estimateGroupBox)

        self.retranslateUi(tagItem)
        QtCore.QMetaObject.connectSlotsByName(tagItem)

    def retranslateUi(self, tagItem):
        _translate = QtCore.QCoreApplication.translate
        tagItem.setWindowTitle(_translate("tagItem", "Frame"))
        self.deviceGroupBox.setTitle(_translate("tagItem", "Device"))
        self.tagIdLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.tagIdLabel.setText(_translate("tagItem", "Tag ID:"))
        self.portLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.portLabel.setText(_translate("tagItem", "Port:"))
        self.positionGroupBox.setTitle(_translate("tagItem", "Position"))
        self.yLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.xLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.zLabel.setText(_translate("tagItem", "z (m):"))
        self.yLabel.setText(_translate("tagItem", "y (m):"))
        self.zLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.xLabel.setText(_translate("tagItem", "x (m):"))
        self.estimateGroupBox.setTitle(_translate("tagItem", "Estimate"))
        self.yEstLabel.setText(_translate("tagItem", "y (m):"))
        self.zEstLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.xEstLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.zEstLabel.setText(_translate("tagItem", "z (m):"))
        self.xEstLabel.setText(_translate("tagItem", "x (m):"))
        self.yEstLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.rollEstLabel.setText(_translate("tagItem", "R (rad):"))
        self.rollEstLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.pitchEstLabel.setText(_translate("tagItem", "P (rad):"))
        self.pitchEstLabelValue.setText(_translate("tagItem", "TextLabel"))
        self.yawEstLabel.setText(_translate("tagItem", "Y (rad):"))
        self.yawEstLabelValue.setText(_translate("tagItem", "TextLabel"))

